const MANGA = [
    {
        id: 1,
        series: "BLEACH",
        name: ["CONQUISTADORES"],
        volume: 22,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл22.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 2,
        series: "BLEACH",
        name: ["MALA SUERTE"],
        volume: 23,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл23.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 3,
        series: "BLEACH",
        name: ["THE MASCARON DRIVE"],
        volume: 26,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл26.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 4,
        series: "BLEACH",
        name: ["GOOBYE, HALCYON DAYS"],
        volume: 27,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл27.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 5,
        series: "BLEACH",
        name: ["BARON'S LECTURE FULL-COURSE"],
        volume: 28,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл28.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 6,
        series: "BLEACH",
        name: ["KINGDOM OF HOLLOWS"],
        volume: 43,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл43.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 7,
        series: "BLEACH",
        name: ["VICE IT"],
        volume: 44,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл44.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 8,
        series: "BLEACH",
        name: ["THE BURNOUT INFERNO"],
        volume: 45,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл45.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 9,
        series: "BLEACH",
        name: ["LOVE ME BITTERLY LOTH ME SWEETLY"],
        volume: 51,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл51.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 10,
        series: "BLEACH",
        name: ["END OF BOND"],
        volume: 52,
        author: ["TITO KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл52.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 11,
        series: "МАГИЧЕСКАЯ БИТВА",
        name: ["ОСЛЕПИТЕЛЬНАЯ ТЬМА"],
        volume: 0,
        author: ["ГЭГЭ АКУТАМИ"],
        publisher: "АЗБУКА",
        img: "./images/мб0.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "ДРАМА"],
        price: 500
    },
    {
        id: 12,
        series: "МАГИЧЕСКАЯ БИТВА",
        name: ["ДВУЛИКИЙ СУКУНА", "ПРОКЛЯТЫЙ ПЛОД"],
        volume: 1,
        author: ["ГЭГЭ АКУТАМИ"],
        publisher: "АЗБУКА",
        img: "./images/мб1.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "ДРАМА"],
        price: 500
    },
    {
        id: 13,
        series: "МАГИЧЕСКАЯ БИТВА",
        name: ["МЕЛКАЯ РЫБЕШКА И ВОЗДАЯНИЕ", "Я УБЬЮ ТЕБЯ!"],
        volume: 2,
        author: ["ГЭГЭ АКУТАМИ"],
        publisher: "АЗБУКА",
        img: "./images/мб2.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "ДРАМА"],
        price: 500
    },
    {
        id: 14,
        series: "МАГИЧЕСКАЯ БИТВА",
        name: ["КОМАНДНЫЙ БОЙ", "ЧЕРНАЯ ВСПЫШКА"],
        volume: 3,
        author: ["ГЭГЭ АКУТАМИ"],
        publisher: "АЗБУКА",
        img: "./images/мб3.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "ДРАМА"],
        price: 500
    },
    {
        id: 15,
        series: "МАГИЧЕСКАЯ БИТВА",
        name: ["НАЧАЛО ПОВИНОВЕНИЯ", "ПАГУБНЫЙ ТАЛАНТ"],
        volume: 4,
        author: ["ГЭГЭ АКУТАМИ"],
        publisher: "АЗБУКА",
        img: "./images/мб4.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "ДРАМА"],
        price: 500
    },
    {
        id: 16,
        series: "МАГИЧЕСКАЯ БИТВА",
        name: ["ТАЛАНТЫ УМИРАЮТ МОЛОДЫМИ", "В ПРЕДДВЕРИИ ПРАЗДНИКА"],
        volume: 5,
        author: ["ГЭГЭ АКУТАМИ"],
        publisher: "АЗБУКА",
        img: "./images/мб5.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "ДРАМА"],
        price: 500
    },
    {
        id: 17,
        series: "ТОКИЙСКИЙ ГУЛЬ",
        name: ["ТОКИЙСКИЙ ГУЛЬ"],
        volume: 1,
        author: ["СУИ ИСИДА"],
        publisher: "АЗБУКА",
        img: "./images/тг1.jpg",
        genre: ["СЭЙНЭН", "БОЕВИК", "ДРАМА", "ПСИХОЛОГИЯ"],
        price: 500
    },
    {
        id: 18,
        series: "ТОКИЙСКИЙ ГУЛЬ",
        name: ["ТОКИЙСКИЙ ГУЛЬ"],
        volume: 2,
        author: ["СУИ ИСИДА"],
        publisher: "АЗБУКА",
        img: "./images/тг2.jpg",
        genre: ["СЭЙНЭН", "БОЕВИК", "ДРАМА", "ПСИХОЛОГИЯ"],
        price: 500
    },
    {
        id: 19,
        series: "ТОКИЙСКИЙ ГУЛЬ",
        name: ["ТОКИЙСКИЙ ГУЛЬ"],
        volume: 3,
        author: ["СУИ ИСИДА"],
        publisher: "АЗБУКА",
        img: "./images/тг3.jpg",
        genre: ["СЭЙНЭН", "БОЕВИК", "ДРАМА", "ПСИХОЛОГИЯ"],
        price: 500
    },
    {
        id: 20,
        series: "ТОКИЙСКИЙ ГУЛЬ",
        name: ["[ZAKKI]"],
        volume: -1,
        author: ["СУИ ИСИДА"],
        publisher: "АЗБУКА",
        img: "./images/тгzakki.jpg",
        genre: ["СЭЙНЭН", "БОЕВИК", "ДРАМА", "ПСИХОЛОГИЯ"],
        price: 500
    },
    {
        id: 21,
        series: "ДЗЮНДЗИ ИТО:ИСТОРИИ",
        name: ["ЛЮБОВЬ МЕРТВЕЦА"],
        volume: -1,
        author: ["ДЗЮНДЗИ ИТО"],
        publisher: "АЗБУКА",
        img: "./images/лм.jpg",
        genre: ["МИСТИКА", "СВЕРХЪЕСТЕСТВЕННОЕ", "УЖАСЫ"],
        price: 500
    },
    {
        id: 22,
        series: "ДЗЮНДЗИ ИТО:ИСТОРИИ",
        name: ["БЕЗГОЛОВЫЕ СТАТУИ"],
        volume: -1,
        author: ["ДЗЮНДЗИ ИТО"],
        publisher: "АЗБУКА",
        img: "./images/бс.jpg",
        genre: ["МИСТИКА", "СВЕРХЪЕСТЕСТВЕННОЕ", "УЖАСЫ"],
        price: 500
    },
    {
        id: 23,
        series: "ДЗЮНДЗИ ИТО:ИСТОРИИ",
        name: ["СТОН СЛИВНОЙ ТРУБЫ"],
        volume: -1,
        author: ["ДЗЮНДЗИ ИТО"],
        publisher: "АЗБУКА",
        img: "./images/сст.jpg",
        genre: ["МИСТИКА", "СВЕРХЪЕСТЕСТВЕННОЕ", "УЖАСЫ"],
        price: 500
    },
    {
        id: 24,
        series: "ДЗЮНДЗИ ИТО:ИСТОРИИ",
        name: ["ПЕРЕУЛОК"],
        volume: -1,
        author: ["ДЗЮНДЗИ ИТО"],
        publisher: "АЗБУКА",
        img: "./images/пе.jpg",
        genre: ["МИСТИКА", "СВЕРХЪЕСТЕСТВЕННОЕ", "УЖАСЫ"],
        price: 500
    },
    {
        id: 25,
        series: "ДЗЮНДЗИ ИТО:ИСТОРИИ",
        name: ["ДЕЗЕРТИР"],
        volume: -1,
        author: ["ДЗЮНДЗИ ИТО"],
        publisher: "АЗБУКА",
        img: "./images/де.jpg",
        genre: ["МИСТИКА", "СВЕРХЪЕСТЕСТВЕННОЕ", "УЖАСЫ"],
        price: 500
    },
    {
        id: 26,
        series: "ДЗЮНДЗИ ИТО:ИСТОРИИ",
        name: ["ГОРОД НАДГРОБИЙ"],
        volume: -1,
        author: ["ДЗЮНДЗИ ИТО"],
        publisher: "АЗБУКА",
        img: "./images/гн.jpg",
        genre: ["МИСТИКА", "СВЕРХЪЕСТЕСТВЕННОЕ", "УЖАСЫ"],
        price: 500
    },
    {
        id: 27,
        series: "ГАНГСТА",
        name: ["ГАНГСТА"],
        volume: 1,
        author: ["КОСКЭ"],
        publisher: "АСТ",
        img: "./images/га.jpg",
        genre: ["МАФИЯ", "БОЕВИК", "СЭЙНЭН"],
        price: 500
    },
    {
        id: 28,
        series: "СОЗДАННЫЙ В БЕЗДНЕ",
        name: ["СОЗДАННЫЙ В БЕЗДНЕ"],
        volume: 1,
        author: ["АКИХИТО ЦУКУСИ"],
        publisher: "АСТ",
        img: "./images/свб.jpg",
        genre: ["НАУЧНАЯ ФАНТАСТИКА", "ДРАМА", "СЭЙНЭН", "ФЭНТЕЗИ"],
        price: 500
    },
    {
        id: 29,
        series: "ЧЕЛОВЕК-БЕНЗОПИЛА",
        name: ["ПЕС И БЕНЗОПИЛА", "БЕНЗОПИЛА ПРОТИВ НЕТОПЫРЯ"],
        volume: 1,
        author: ["ТАЦУКИ ФУДЗИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/чб1.jpg",
        genre: ["БОЕВИК", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 30,
        series: "ЧЕЛОВЕК-БЕНЗОПИЛА",
        name: ["УБИТЬ ДЕНДЗИ", "МОЩЬ ОГНЕСТРЕЛЬНОГО ОРУЖИЯ"],
        volume: 2,
        author: ["ТАЦУКИ ФУДЗИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/чб2.jpg",
        genre: ["БОЕВИК", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 31,
        series: "ЧЕЛОВЕК-БЕНЗОПИЛА",
        name: ["НЕСОВЕРШЕННОЛЕТНИЙ", "БУМ-БУМ-БУМ"],
        volume: 3,
        author: ["ТАЦУКИ ФУДЗИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/чб3.jpg",
        genre: ["БОЕВИК", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 32,
        series: "ЧЕЛОВЕК-БЕНЗОПИЛА",
        name: ["ВО СНЕ", "НАСТОЯЩАЯ ЖЕСТЬ"],
        volume: 4,
        author: ["ТАЦУКИ ФУДЗИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/чб4.jpg",
        genre: ["БОЕВИК", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 33,
        series: "ЧЕЛОВЕК-БЕНЗОПИЛА",
        name: ["КУПАНИЕ В ВАННЕ", "ЧУВСТВА СОБАКИ"],
        volume: 5,
        author: ["ТАЦУКИ ФУДЗИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/чб5.jpg",
        genre: ["БОЕВИК", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 34,
        series: "ЧЕЛОВЕК-БЕНЗОПИЛА",
        name: ["ВПЕРЕД, ЧЕЛОВЕК БЕНЗОПИЛА"],
        volume: 6,
        author: ["ТАЦУКИ ФУДЗИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/чб6.jpg",
        genre: ["БОЕВИК", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 35,
        series: "ЧЕЛОВЕК-БЕНЗОПИЛА",
        name: ["ПТИЦА И ВОЙНА"],
        volume: 7,
        author: ["ТАЦУКИ ФУДЗИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/чб7.jpg",
        genre: ["БОЕВИК", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 36,
        series: "ЗОВ АДА",
        name: ["ЗОВ АДА"],
        volume: 1,
        author: ["ЁН САНХО", "ЧХВЕ КЮСОК"],
        publisher: "АЗБУКА",
        img: "./images/за1.jpg",
        genre: ["ТРИЛЛЕР", "ДЕТЕКТИВ", "МИСТИКА", "СЭЙНЭН"],
        price: 500
    },
    {
        id: 37,
        series: "DEATH NOTE",
        name: ["BLACK EDITION"],
        volume: 1,
        author: ["ЦУГУМИ ООБА", "ТАКЭСИ ОБАТА"],
        publisher: "АЗБУКА",
        img: "./images/тс1.jpg",
        genre: ["БОЕВИК", "ДЕТЕКТИВ", "ДРАМА", "СЕНЭН"],
        price: 500
    },
    {
        id: 38,
        series: "НАРУТО",
        name: ["ВЕРНЫЙ ПУТЬ"],
        volume: 3,
        author: ["МАСАСИ КИСИМОТО"],
        publisher: "АЗБУКА",
        img: "./images/на3.jpg",
        genre: ["БОЕВИК", "ДРАМА", "КОМЕДИЯ", "СЕНЭН"],
        price: 500
    },
    {
        id: 39,
        series: "НЕОБЪЯТНЫЙ ОКЕАН",
        name: ["НЕОБЪЯТНЫЙ ОКЕАН"],
        volume: 1,
        author: ["ИНОУЭ КЭНДЗИ", "ЁСИОКА КИМИТАКЭ"],
        publisher: "ФАНТАСТИКА КНИЖНЫЙ КЛУБ",
        img: "./images/но1.jpg",
        genre: ["КОМЕДИЯ", "СЭЙНЭН", "ЭТТИ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 40,
        series: "АТАКА НА ТИТАНОВ",
        name: ["АТАКА НА ТИТАНОВ"],
        volume: 1,
        author: ["ХАДЗИМЕ ИСАЯМА"],
        publisher: "АЗБУКА",
        img: "./images/ант1.jpg",
        genre: ["СЕНЭН", "УЖАСЫ", "ФЭНТЕЗИ"],
        price: 500
    },
    {
        id: 41,
        series: "АТАКА НА ТИТАНОВ",
        name: ["АТАКА НА ТИТАНОВ"],
        volume: 2,
        author: ["ХАДЗИМЕ ИСАЯМА"],
        publisher: "АЗБУКА",
        img: "./images/ант2.jpg",
        genre: ["СЕНЭН", "УЖАСЫ", "ФЭНТЕЗИ"],
        price: 500
    },
    {
        id: 42,
        series: "ПРИЗРАК В ДОСПЕХАХ",
        name: ["ПРОЦЕССОР С ЧЕЛОВЕЧЕСКОЙ ПОГРЕШНОСТЬЮ"],
        volume: 1.5,
        author: ["СИРО МАСАМУНЭ"],
        publisher: "АЗБУКА",
        img: "./images/пвд1.5.jpg",
        genre: ["СЭЙНЭН", "ФАНТАСТИКА", "ЭКШЕН"],
        price: 500
    },
    {
        id: 43,
        series: "BLEACH",
        name: ["DEATH AND THE STRAWBERRY"],
        volume: 1,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл1.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 44,
        series: "BLEACH",
        name: ["GOODBYE PARAKEET, GOODNITE MY SISTA"],
        volume: 2,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл2.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 45,
        series: "BLEACH",
        name: ["MEMORIES IN THE RAIN"],
        volume: 3,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл3.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 46,
        series: "BLEACH",
        name: ["QUINCY ARCHER HATES YOU"],
        volume: 4,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл4.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 47,
        series: "BLEACH",
        name: ["RIGHTARM OF THE GIANT"],
        volume: 5,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл5.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 48,
        series: "BLEACH",
        name: ["THE DEATH TRILOGY OVERTURE"],
        volume: 6,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл6.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 49,
        series: "BLEACH",
        name: ["THE BROKEN CODA"],
        volume: 7,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл7.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 50,
        series: "BLEACH",
        name: ["THE BLADE AND ME"],
        volume: 8,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл8.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 51,
        series: "BLEACH",
        name: ["TOURTEEN DAYS FOR CONSPIRACY"],
        volume: 9,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл9.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 52,
        series: "BLEACH",
        name: ["TATTOO ON THE SKY"],
        volume: 10,
        author: ["TITE KUBO"],
        publisher: "JUMP COMICS",
        img: "./images/бл10.jpg",
        genre: ["СЕНЭН", "БОЕВИК", "КОМЕДИЯ", "ДРАМА"],
        price: 500
    },
    {
        id: 53,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 1,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп1.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 54,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 2,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп2.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 55,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 3,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп3.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 56,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 4,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп4.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 57,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 5,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп5.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 58,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 6,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп6.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 59,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 7,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп7.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 60,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 8,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп8.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 61,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 9,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп9.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 62,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 10,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп10.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 63,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 11,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп11.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 64,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 12,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп12.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    },
    {
        id: 65,
        series: "ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ",
        name: ["ЧУДОВИЩЕ ЗА СОСЕДНЕЙ ПАРТОЙ"],
        volume: 13,
        author: ["РОБИКО"],
        publisher: "XL MEDIA",
        img: "./images/чзсп13.jpg",
        genre: ["СЁДЗЁ", "КОМЕДИЯ", "РОМАНТИКА"],
        price: 500
    }
];